services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /C//docker-data/bagetter-compose-demo/mysql:/var/lib/mysql
    networks:
      - bagetter-net
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: bagetter
      MYSQL_USER: bagetter
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_bagetter_password
    secrets:
      - mysql_root_password
      - mysql_bagetter_password

  bagetter:
    depends_on:
      - database
    image: bagetter/bagetter
    ports:
      - "8080:8080"
    volumes:
      - /C//docker-data/bagetter-compose-demo/packages:/data     
    networks:
      - bagetter-net
    env_file: 
      - ./.secrets/bagetter.env

networks:
  # The presence of these objects is sufficient to define them
  bagetter-net: {}
    
secrets:
  mysql_root_password: 
    file: ./.secrets/mysql_root_password.txt
  mysql_bagetter_password:
    file: ./.secrets/mysql_bagetter_password.txt
